export const metadata = {
  title: "A1xf | Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <main>
      <h1>Home page!</h1>
    </main>
  );
}
