import Post from "../component/Post";
import getAllPosts from "../lib/getAllPosts";

export const metadata = {
  title: "A1xf | Posts",
  description: "Generated by create next app",
};

export default async function PostsPage() {
  const posts = await getAllPosts();

  return (
    <div className="max-w-screen-xl mt-20 mx-auto">
      <h1>PostsPage</h1>
      <div className="grid lg:grid-cols-3 gap-10 justify-items-center">
        {posts.map((post) => (
          <Post key={post.id} post={post}></Post>
        ))}
      </div>
    </div>
  );
}
