import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/share/Navbar";
import Footer from "./components/share/Footer";
import { Container } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navbar></Navbar>
        </div>
        <Container className="min-h-screen">{children}</Container>
        <div>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
